baseURL = "http://localhost"

contentDir = "docs"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Hugo Asciidoc Test"
theme = "ananke"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[markup.asciidocext]
    extensions = ["asciidoctor-html5s", "asciidoctor-diagram"]
    backend = "html5s"
    workingFolderCurrent = true
    trace = true

#[module]
#[[module.imports]]
#    path="github.com/muenchhausen/hugo_asciidoc_chapter3"
#[[module.imports.mounts]]
#    source="source/chapter3"
#    target="content/chapter3"

[Params]

    # Souce Code repository section
    description = "DDD Template"
    github_repository = "https://github.com/muenchhausen/hugo_asciidoc_ddd"
    version = "1.0.0"

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "entry", "post", "posts"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Chapter 1"
    url = "/chapter1"
    weight = 2

[[menu.main]]
    name = "Chapter 2"
    url = "/chapter2"
    weight = 3

#[[menu.main]]
#    name = "Chapter 3"
#    url = "/chapter3"
#    weight = 3

[[menu.main]]
    name = "TOC sample"
    url = "/tocsample"
    weight = 4

[[menu.main]]
    name = "Book as PDF"
    url = "http://localhost:1313/book-as-pdf.pdf"
    weight = 10

[[menu.main]]
    name = "Book as HTML (wrong imagesdir)"
    url = "/book-as-pdf"
    weight = 10

[outputs]
  home = ["HTML", "JSON"]
